import random

from fastapi import APIRouter, Depends

import backend.crud.answer as answer_crud
import backend.crud.progress as progress_crud
import backend.crud.user as user_crud
from backend.db.session import SessionLocal
from backend.schemas.answer import AnswerCreate
from backend.schemas.progress import ProgressCreate
from backend.schemas.user import UserCreate

departments = ["D2", "INTL", "APD", "SD", "stmn", "幹部", "other"]
AnswerList = [
    [
        "北海道",
        "青森県",
        "岩手県",
        "宮城県",
        "秋田県",
        "山形県",
        "福島県",
        "茨城県",
        "栃木県",
        "群馬県",
        "埼玉県",
        "千葉県",
        "東京都",
        "神奈川県",
        "新潟県",
        "富山県",
        "石川県",
        "福井県",
        "山梨県",
        "長野県",
        "岐阜県",
        "静岡県",
        "愛知県",
        "三重県",
        "滋賀県",
        "京都府",
        "大阪府",
        "兵庫県",
        "奈良県",
        "和歌山県",
        "鳥取県",
        "島根県",
        "岡山県",
        "広島県",
        "山口県",
        "徳島県",
        "香川県",
        "愛媛県",
        "高知県",
        "福岡県",
        "佐賀県",
        "長崎県",
        "熊本県",
        "大分県",
        "宮崎県",
        "鹿児島県",
        "沖縄県",
    ],
    [
        "陸上",
        "水泳",
        "サッカー",
        "テニス",
        "ローイング",
        "ホッケー",
        "ボクシング",
        "バレーボール",
        "体操",
        "バスケットボール",
        "レスリング",
        "セーリング",
        "ウェイトリフティング",
        "ハンドボール",
        "自転車",
        "卓球",
        "馬術",
        "フェンシング",
        "柔道",
        "バドミントン",
        "射撃",
        "近代五種",
        "ラグビー",
        "カヌー",
        "アーチェリー",
        "トライアスロン",
        "ゴルフ",
        "テコンドー",
        "スポーツクライミング",
        "サーフィン",
        "スケートボード",
        "ブレイキン",
        "車いすテニス",
        "車いすバスケットボール",
        "車いすフェンシング",
        "車いすラグビー",
        "ゴールボール",
        "シッティングバレーボール",
        "ブラインドサッカー",
        "ボッチャ",
    ],
    [
        "Python",
        "JavaScript",
        "Java",
        "C#",
        "C++",
        "Ruby",
        "Swift",
        "Kotlin",
        "TypeScript",
        "PHP",
        "Go",
        "Rust",
        "Dart",
        "Scala",
        "Perl",
        "R",
        "MATLAB",
        "Julia",
        "Haskell",
        "Lua",
        "Objective-C",
        "Groovy",
        "Elixir",
        "Erlang",
        "F#",
        "Clojure",
        "Shell Script",
        "SQL",
        "PL/SQL",
        "Apex",
        "Visual Basic .NET",
        "Assembly Language",
        "COBOL",
        "Fortran",
        "Ada",
        "VHDL",
        "Verilog",
        "Prolog",
        "Scheme",
        "OCaml",
    ],
    [
        "犬",
        "猫",
        "ウサギ",
        "ハムスター",
        "モルモット",
        "フェレット",
        "インコ",
        "カナリア",
        "オウム",
        "チンチラ",
        "デグー",
        "リス",
        "モモンガ",
        "カメ",
        "トカゲ",
        "ヘビ",
        "カエル",
        "イグアナ",
        "ヤモリ",
        "フクロウ",
        "ハヤブサ",
        "ハト",
        "メダカ",
        "グッピー",
        "ベタ",
        "金魚",
        "コイ",
        "熱帯魚",
        "エビ",
        "カニ",
        "ヤドカリ",
        "ウーパールーパー",
        "カワウソ",
        "ミーアキャット",
        "アルパカ",
        "ヤギ",
        "ヒツジ",
        "ポニー",
        "ミニブタ",
        "スナネズミ",
        "シマリス",
        "フェネック",
        "コアラ",
        "カンガルー",
        "パンダ",
        "レッサーパンダ",
        "キツネ",
        "ハリネズミ",
        "カメレオン",
        "ヤドカリ",
    ],
    [
        "あ",
        "い",
        "う",
        "え",
        "お",
        "か",
        "き",
        "く",
        "け",
        "こ",
        "さ",
        "し",
        "す",
        "せ",
        "そ",
        "た",
        "ち",
        "つ",
        "て",
        "と",
        "な",
        "に",
        "ぬ",
        "ね",
        "の",
        "は",
        "ひ",
        "ふ",
        "へ",
        "ほ",
        "ま",
        "み",
        "む",
        "め",
        "も",
        "や",
        "ゆ",
        "よ",
        "ら",
        "り",
        "る",
        "れ",
        "ろ",
        "わ",
        "を",
        "ん",
    ],
    [
        "北海道",
        "青森県",
        "岩手県",
        "宮城県",
        "秋田県",
        "山形県",
        "福島県",
        "茨城県",
        "栃木県",
        "群馬県",
        "埼玉県",
        "千葉県",
        "東京都",
        "神奈川県",
        "新潟県",
        "富山県",
        "石川県",
        "福井県",
        "山梨県",
        "長野県",
        "岐阜県",
        "静岡県",
        "愛知県",
        "三重県",
        "滋賀県",
        "京都府",
        "大阪府",
        "兵庫県",
        "奈良県",
        "和歌山県",
        "鳥取県",
        "島根県",
        "岡山県",
        "広島県",
        "山口県",
        "徳島県",
        "香川県",
        "愛媛県",
        "高知県",
        "福岡県",
        "佐賀県",
        "長崎県",
        "熊本県",
        "大分県",
        "宮崎県",
        "鹿児島県",
        "沖縄県",
    ],
]


def prepare() -> None:
    db = SessionLocal()

    # ユーザーの作成
    n = 190
    for i in range(n):
        user = UserCreate(
            first_name="user",
            last_name=f"{i}",
            department=random.choice(departments),
        )
        user_crud.create_user(db, user=user)

    # 進捗管理の作成
    progress = ProgressCreate(status=0)
    progress_crud.create_progress(db, progress=progress)

    # 回答の作成
    for q in range(6):
        for i in range(n):
            answer = AnswerCreate(
                user_id=i + 1, question_id=q, content=random.choice(AnswerList[q])
            )
            answer_crud.create_answer(db, answer=answer)


prepare()
